language: php
sudo: false
matrix:
  fast_finish: true
cache:
- vendor
- bin
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_script:
- composer install
- mkdir -p build/logs
script: bin/phpunit
after_script:
- bin/coveralls -v
after_success:
- wget "https://github.com/aktau/github-release/releases/download/v0.5.3/linux-amd64-github-release.tar.bz2"
- tar xvf linux-amd64-github-release.tar.bz2
- make release
- make deploy
